package com.syuct.core_service.protoc.db;

import java.util.Date;

public class OfflineMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.message_from
     *
     * @mbg.generated
     */
    private String messageFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.message_to
     *
     * @mbg.generated
     */
    private String messageTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.message_content
     *
     * @mbg.generated
     */
    private String messageContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.message_status
     *
     * @mbg.generated
     */
    private String messageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.addTime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    public OfflineMessage() {
    }

    public Integer getId() {
        return id;
    }

    public OfflineMessage setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getMessageFrom() {
        return messageFrom;
    }

    public OfflineMessage setMessageFrom(String messageFrom) {
        this.messageFrom = messageFrom;
        return this;
    }

    public String getMessageTo() {
        return messageTo;
    }

    public OfflineMessage setMessageTo(String messageTo) {
        this.messageTo = messageTo;
        return this;
    }

    public String getMessageContent() {
        return messageContent;
    }

    public OfflineMessage setMessageContent(String messageContent) {
        this.messageContent = messageContent;
        return this;
    }

    public String getMessageStatus() {
        return messageStatus;
    }

    public OfflineMessage setMessageStatus(String messageStatus) {
        this.messageStatus = messageStatus;
        return this;
    }

    public Date getAddtime() {
        return addtime;
    }

    public OfflineMessage setAddtime(Date addtime) {
        this.addtime = addtime;
        return this;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public OfflineMessage setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
        return this;
    }
}